    %A) Sinal (y(t))^2 gerado.
    
    [y_Gcdys_impulse_classico,...
        t_Gcdys_impulse_classico,...
        x_Gcdys_impulse_classico]=...
            impulse(Gcdys_classico,tempo_simulacao_impulso);
    
    y2_Gcdys_impulse_classico=...
        y_Gcdys_impulse_classico.*y_Gcdys_impulse_classico;
    
    %B) Sinal u(t) gerado.
    
    u_Gcdys_impulse_classico(1:size(x_Gcdys_impulse_classico,1),1:n_u,1)=...
        x_Gcdys_impulse_classico(:,:,1)*Kpf_classico';
    
    u2_Gcdys_impulse_classico=u_Gcdys_impulse_classico.*u_Gcdys_impulse_classico;
